import Head from 'next/head'
import { Hero, Navbar, Gallery, Footer, MobileNav } from '@/components'
import { useAppDispatch } from '@/redux/store/reduxHooks'
import { resetUserState } from '@/redux/slices/userSlice'
import { useMobileMenuIsOpen } from '@/hooks/hooksIndex'

export default function Home() {
  const dispatch = useAppDispatch()
  const mobileMenuIsOpen = useMobileMenuIsOpen()
  dispatch(resetUserState())

  return (
    <>
      <Head>
        <title>Curry Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {mobileMenuIsOpen ? <MobileNav /> : null}
      {mobileMenuIsOpen ? null : <Navbar />}
      {mobileMenuIsOpen ? null : <Hero />}
      {mobileMenuIsOpen ? null : <Gallery />}
      {mobileMenuIsOpen ? null : <Footer />}
    </>
  )
}
